# Generated by Django 5.0.4 on 2024-05-05 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datasetApp', '0003_tag_alter_datasettag_name_alter_dataset_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DatasetDatasetTag',
        ),
        migrations.DeleteModel(
            name='DatasetTag',
        ),
    ]
