# Generated by Django 5.0.4 on 2024-05-09 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasetApp', '0007_rename_name_model_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datasetApp.domain'),
        ),
    ]
