# Generated by Django 5.0.4 on 2024-05-10 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasetApp', '0008_model_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelvote',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_votes', to='datasetApp.model'),
        ),
    ]
