# Generated by Django 5.0.4 on 2024-05-10 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasetApp', '0009_alter_modelvote_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelfile',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datasetApp.model'),
        ),
    ]
