# Generated by Django 5.0.4 on 2024-05-10 13:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasetApp', '0010_modelfile_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='model',
            name='tags',
            field=models.ManyToManyField(to='datasetApp.tag'),
        ),
        migrations.AddField(
            model_name='model',
            name='total_files',
            field=models.IntegerField(default=14),
        ),
        migrations.AddField(
            model_name='model',
            name='updated_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
