# Generated by Django 5.0.4 on 2024-05-10 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasetApp', '0011_model_created_at_model_tags_model_total_files_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelfileextension',
            name='file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='datasetApp.modelfile'),
        ),
    ]
