# Generated by Django 5.0.4 on 2024-05-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasetApp', '0013_remove_modelfile_model_modelfolder_modelfile_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetvote',
            name='isUpvoted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='modelvote',
            name='isUpvoted',
            field=models.BooleanField(default=True),
        ),
    ]
