# Generated by Django 5.0.4 on 2024-05-18 09:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "datasetApp",
            "0016_alter_dataset_size_alter_file_size_alter_model_size_and_more (copy)",
        ),
        ("datasetApp", "0017_alter_dataset_id"),
    ]

    operations = []
