# Generated by Django 5.0.6 on 2024-07-04 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasetApp', '0022_remove_repository_owner_repositoryowners'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositoryowners',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repository_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
