# Generated by Django 5.0.6 on 2024-06-25 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_chatroom_chatmessages'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessages',
            name='created_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='created_date',
            field=models.DateField(auto_now=True),
        ),
    ]
