# Generated by Django 5.0.6 on 2024-06-25 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0003_chatmessages_created_date_chatroom_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='receiver',
        ),
        migrations.DeleteModel(
            name='ChatMessages',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
    ]
